Changed Sign plugin set

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -15,6 +15,7 @@ jobs:
       # GRAFANA_ACCESS_POLICY_TOKEN: ${{ secrets.GRAFANA_ACCESS_POLICY_TOKEN }}
     steps:
       - run: echo ${GITHUB_WORKSPACE}
+      - run: echo ${GRAFANA_ACCESS_POLICY_TOKEN}
       - uses: actions/checkout@v3
 
       # - name: Change Directory
@@ -90,14 +91,23 @@ jobs:
             mage -v build:linux
         working-directory: ${{ github.workspace }}/dfe-azurecostbackend-datasource
 
-      - name: Warn missing Grafana access policy token
+      # - name: Warn missing Grafana access policy token
+      #   run: |
+      #     echo Please generate a Grafana access policy token: https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token
+      #     echo Once done please follow the instructions found here: https://github.com/${{github.repository}}/blob/main/README.md#using-github-actions-release-workflow
+      #   # if: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN == '' }}
+
+      - name: Check Token and Show Message
         run: |
-          echo Please generate a Grafana access policy token: https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token
-          echo Once done please follow the instructions found here: https://github.com/${{github.repository}}/blob/main/README.md#using-github-actions-release-workflow
-        # if: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN == '' }}
+          if [ -z "$GRAFANA_ACCESS_POLICY_TOKEN" ]; then
+            echo "Error: GRAFANA_ACCESS_POLICY_TOKEN is empty. Please set the secret in GitHub. Please generate a Grafana access policy token: https://grafana.com/developers/plugin-tools/publish-a-plugin/sign-a-plugin#generate-an-access-policy-token"
+            exit 1
+          else
+            echo "GRAFANA_ACCESS_POLICY_TOKEN is set: $GRAFANA_ACCESS_POLICY_TOKEN"
+          fi
 
       - name: Sign plugin
-        run: npm run sign
+        run: npx @grafana/sign-plugin@latest --rootUrls http://localhost:3000/
         # if: ${{ env.GRAFANA_ACCESS_POLICY_TOKEN != '' }}
 
       - name: Get plugin metadata
